### ISSUE TITLE
Opening the preview in the queue results in a 500 in Contao 4

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-notification_center#127]
So far notification_center works fine also in Contao 4. Just one thing seems to be not working: After putting a notification to a queue, there's the option to view the details after clicking on the "i"-button. The response throws a 500 and for some reason there's neither an error in the apache logs nor in the contao logs.

I tried to search for a @ in the php files which suppresses the error being thrown with no success.

**Comment by Toflar** [comment]
Can you run the application in `dev` environment and with debug enabled? You can use the `app_dev.php` that will be shipped with Contao 4.4 (https://github.com/contao/manager-bundle/blob/release/4.4.0/src/Resources/web/app_dev.php) and then check everything by using `domain.de/app_dev.php/contao` again.

**Comment by Defcon0** [comment]
Unfortunately I cannot simply use the app_dev.php in my Contao 4.3.11 instance because setProjectDir doesn't exist. Event adding it will result in fail since the property projectdir in ContaoKernel is used widely. Maybe I try in Contao 4.4

**Comment by aschempp** [comment]
You can copy the `app_dev.php` file from a Contao 4.3 standard edition

**Comment by Defcon0** [comment]
Nope, unfortunately not :-)

```
ClassNotFoundException
Attempted to load class "AppKernel" from the global namespace.
```

**Comment by aschempp** [comment]
I'm sorry, stupid me. Easiest should be to duplicate the app.php and change the kernel arguments from «"prod", false» to «"dev", true». 

Be aware that it will not have access protection then, so delete it as soon as you're done.

**Comment by Defcon0** [comment]
Just tried.

After setting the changes you suggested, I still don't have an error message in the HTML, but in the dev-log I have the following (which is probably not useful as I suspect):

`[2017-06-19 09:54:58] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction","_route":"contao_backend"},"request_uri":"http://www.project.customer.hhdev/contao?act=show&do=nc_queue&id=10&popup=1&ref=dezz5mVE&rt=oRaLjcBHrrJZlSpWpceDVVscDQmlO03E4j0XTNji4o4","method":"GET"} []
[2017-06-19 09:54:58] security.INFO: Attempting SimplePreAuthentication. {"key":"backend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2017-06-19 09:54:58] php.INFO: User Deprecated: Using the Contao\ClassLoader class has been deprecated and will no longer work in Contao 5.0. Use the Composer autoloader instead. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): User Deprecated: Using the Contao\\ClassLoader class has been deprecated and will no longer work in Contao 5.0. Use the Composer autoloader instead. at /home/my_user/Kunden/customer/project/produkte/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/ClassLoader.php:13)"} []
[2017-06-19 09:54:58] php.INFO: User Deprecated: Using the Contao\ModuleLoader class has been deprecated and will no longer work in Contao 5.0. Use the container parameter "kernel.bundles" instead. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): User Deprecated: Using the Contao\\ModuleLoader class has been deprecated and will no longer work in Contao 5.0. Use the container parameter \"kernel.bundles\" instead. at /home/my_user/Kunden/customer/project/produkte/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/ModuleLoader.php:13)"} []
[2017-06-19 09:54:58] php.INFO: User Deprecated: Using the Contao\RequestToken class has been deprecated and will no longer work in Contao 5.0. Use the Symfony CSRF service via the container instead. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): User Deprecated: Using the Contao\\RequestToken class has been deprecated and will no longer work in Contao 5.0. Use the Symfony CSRF service via the container instead. at /home/my_user/Kunden/customer/project/produkte/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/RequestToken.php:15)"} []
[2017-06-19 09:54:58] php.CRITICAL: Uncaught Exception: Unable to process an ESI tag without a "src" attribute. {"exception":"[object] (RuntimeException(code: 0): Unable to process an ESI tag without a \"src\" attribute. at /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/Esi.php:95)"} []
[2017-06-19 09:54:58] php.CRITICAL: Uncaught Exception: Request stack is empty {"exception":"[object] (LogicException(code: 0): Request stack is empty at /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:99, RuntimeException(code: 0): Unable to process an ESI tag without a \"src\" attribute. at /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/Esi.php:95)"} []
[2017-06-19 09:54:58] php.CRITICAL: Fatal Error: Uncaught RuntimeException: Unable to process an ESI tag without a "src" attribute. in /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/Esi.php:95 Stack trace: #0 /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php(644): Symfony\Component\HttpKernel\HttpCache\Esi->process(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpFoundation\Response)) #1 /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php(494): Symfony\Component\HttpKernel\HttpCache\HttpCache->processResponseBody(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpFoundation\Response)) #2 /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/HttpCache/HttpCache.php(60): Symfony\Component\HttpKernel {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Uncaught RuntimeException: Unable to process an ESI tag without a \"src\" attribute. in /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/Esi.php:95\nStack trace:\n#0 /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php(644): Symfony\\Component\\HttpKernel\\HttpCache\\Esi->process(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#1 /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php(494): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->processResponseBody(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#2 /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/HttpCache/HttpCache.php(60): Symfony\\Component\\HttpKernel at /home/my_user/Kunden/customer/project/produkte/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:99)"} []
`

**Comment by aschempp** [comment]
I cannot reproduce this, at least not in Contao 4.4. Can you post the tokens of your queued message?

**Comment by Defcon0** [comment]
In contao 4.4 it works, so at least for us this is not a problem anymore ;-) Thanks for your support!
